### ISSUE TITLE
setTxPower issue

### ISSUE THREAD

**Issue by Nick7034** [sllurp/sllurp#183]
Hello,
I am new to Sllurp and I am trying to set a certain voltage to run my FX9600 antenna. For some reason, when I set TxPower to index 1 and 2, which are the lowest and highest voltages, I get the same amount of tag readings (only 3), which is not correct. At a lower voltage, I should be reading around 3 tags, and at a higher voltage, I should be reading around 60. I have pasted my code below. Is this how it should be done? I know I can adjust the power through the command line, but it would be better to do it through code. Any help is appreciated.

--------------------------------------------------------------------------------------------------------

    
    from sllurp import llrp
    from sllurp.llrp import LLRPReaderConfig, LLRPReaderClient, LLRP_DEFAULT_PORT, LLRPReaderState
    import time
    import logging
    
    logging.basicConfig(level=logging.DEBUG)
    logger = logging.getLogger(__name__)
    
    def tag_report_cb(reader, tag_reports):
        count = 0
        for tag in tag_reports:
            count += 1
            print('tag: %r' % tag)
        print('total tags scanned: ', count)
    
    uhfbandcap = {
        'TransmitPowerLevelTableEntry': [
            {'Index': 1, 'TransmitPowerValue': 1000},  #10 Dbm
            {'Index': 2, 'TransmitPowerValue': 3000},  #30 Dbm
        ]
    }
    door_open=True
    config = LLRPReaderConfig()
    reader = LLRPReaderClient('IP_Address', LLRP_DEFAULT_PORT, config)
    reader.add_tag_report_callback(tag_report_cb) 
    
    reader.llrp.tx_power_table = reader.llrp.parsePowerTable(uhfbandcap)
    
    print(reader.llrp.tx_power_table)
    
    
    if door_open:
        reader.llrp.setTxPower({1: 1})
    
    reader.connect()
    
    time.sleep(2)
    reader.disconnect()

**Comment by fviard** [comment]
Sorry for the long delay for my reply, there are multiple reasons to your problems:
- First, you can't use "setTxPower()" before the first connection to the reader, because we need to retrieve their power table to know which index to use.
  But you can set the configuration with the power that you want before starting the reader, like you did or directly modifying the "config" object in your example:
 like config.tx_power =2
or config.tx_power_dbm = 15

- As a tip, you can use a "int" value directly and not a dict if you don't care about having different power for different antenna.

- Also, when setting up the configuration, you can indicate the power that you want in dbm and we will find and use the closest available power.

- you can't and should not use `parsePowerTable()` directly, it will not make sense because we are just using "power indexes" to communicate with the reader. So, if you set your own power table, the index we will use will maybe not match with the real power set by this reader for this index.
